---
# tasks file for dbd_sybase

- name: DBD Sybase
  copy:
    directory_mode: True
    src: DBD-Sybase-1.15.tar.gz
    dest: /tmp/
  when: (mssql_sns == "true") or (multi_banco == "true")
  tags:
    - dbd_sybase

- name: Compilando DBD Sybase
  shell: |

    # log do driver
    LOG=/tmp/dbd_sybase.out

    export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

    # Variáveis de ambiente
    export LD_LIBRARY_PATH=/usr/local/freetds:/usr/local/freetds/lib
    export SYBASE=/usr/local/freetds

    tar xzvf /tmp/DBD-Sybase-1.15.tar.gz -C /usr/local/ 1>> "${LOG}" 2>> "${LOG}"

    chown -Rv root:root /usr/local/DBD-Sybase-1.15 1>> "${LOG}" 2>> "${LOG}"

    cd /usr/local/DBD-Sybase-1.15

    echo -e \n\n\n\n\n\n | perl Makefile.PL 1>> "${LOG}" 2>> "${LOG}"
    make 1>> "${LOG}" 2>> "${LOG}"
    make install 1>> "${LOG}" 2>> "${LOG}"
  args:
    executable: /bin/bash
    creates: /tmp/dbd_sybase.out
  when: (mssql_sns == "true") or (multi_banco == "true")
  tags:
    - dbd_sybase
